# -*- coding: utf-8 -*-
"""Actividad6_JoelAlejandroTapiaPerez.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nP-PS0PsjkEAmxu2fNG5vry8S5Fa7rND

Crea una clase llamada Cuenta que tendrá los siguientes atributos: titular (que es una persona) y cantidad (puede tener decimales). El titular será obligatorio y la cantidad es opcional. Construye los siguientes métodos para la clase: 



*   Un constructor.
*   mostrar(): Muestra los datos de la cuenta.
*   ingresar(cantidad): se ingresa una cantidad a la cuenta, si la cantidad introducida es negativa, no se hará nada. 
*   retirar(cantidad): se retira una cantidad a la cuenta. **La cuenta puede estar en números rojos**
"""

class Cuenta:
  def __init__(self,titular,cantidad=0):
    self.titular = titular
    self.cantidad = cantidad

  def mostrar(self):
    print(f"Titular: {self.titular} \nCantidad Disponible: ${self.cantidad}\n")

  def ingresar(self,cantidad):
    if cantidad>=0:
      self.cantidad += cantidad
      print("Ingreso exitoso!")

  def retirar(self,cantidad):
    self.cantidad -= cantidad
    print("Retiro exitoso!")

    # if self.cantidad>=cantidad:
    #   self.cantidad -= cantidad
    #   print("Retiro exitoso!")
    # else:
    #   print(f"La cantidad a retirar es mayor al disponible [${self.cantidad}]\n")

cuenta = Cuenta("Joel Tapia")
cuenta.ingresar(-500)
cuenta.mostrar()

cuenta.ingresar(2500)
cuenta.mostrar()

cuenta.retirar(800)
cuenta.mostrar()

cuenta.retirar(2000)
cuenta.mostrar()